env:
  jest: true

extends:
  - "plugin:prettier/recommended"

rules:
  object-curly-spacing: "off"
  no-unused-expressions: 0
  node/no-deprecated-api: "warn"
  quote-props: "off"
  no-prototype-builtins: "warn"
  array-bracket-spacing: "warn"
  dot-notation: "warn"
